
FROM node:16-alpine as build

WORKDIR /app
COPY . .
RUN yarn
RUN yarn build
EXPOSE 3000
CMD ["yarn", "build"]



FROM nginx:1.22-alpine
RUN mkdir /app

COPY --from=build /app/build /app
COPY ./nginx/default.conf /etc/nginx/conf.d/

EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]