const PATH_URL = {
  LOGIN: "/",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  COMPONENTS: "/components",
  MANAGER_USER: {
    INDEX: "/manager-user",
    TABLE: "",
    EDIT: "edit",
    CREATE: "create",
    DETAIL: "detail",
    OTP: "otp",
  },
  MANAGER_ADMIN: {
    INDEX: "/manager-admin",
    TABLE: "",
    FORM: "form",
    DETAIL: "detail",
    EDIT: "edit",
    CREATE: "create",
  },
  MANAGER_ACCOUNT: {
    INDEX: "/manager-account",
    TABLE: "",
    FORM: "form",
    DETAIL: "detail",
  },
  MANAGER_EVENT: {
    INDEX: "/manager-event",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
    USER_JOIN: "user-join",
  },
  MANAGER_COURSE: {
    INDEX: "/manager-course",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
  MANAGER_COLLECTION: {
    INDEX: "/manager-collection",
    TABLE: "",
    CREATE: "create",
    DETAIL: "detail",
    EDIT: "edit",
  },
  POST: {
    INDEX: "/posts",
    FORM: "form",
    DETAIL: "detail",
  },
  CHECKPOINT: {
    INDEX: "/management-checkpoints",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
  NOTIFICATION: {
    INDEX: "/management-notification",
    TABLE: "",
    CREATE: "create",
    DETAIL: "detail/:id",
  },
  GIFT_CODE: {
    INDEX: "/gift-code",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail/:id",
  },
  BADGE: {
    INDEX: "/badge",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
  SEND_MAIL: {
    INDEX: "/manager-sendmail",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
  DATA_MANAGERMENT: {
    INDEX: "/manager-data",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
  VERSION_MANAGERMENT: {
    INDEX: "/manager-version",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
  },
  GROUP_MANAGERMENT: {
    INDEX: "/manager-group",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
  USERTAG_MANAGERMENT: {
    INDEX: "/manager-usertag",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
  RESULT_IMAGE_MANAGERMENT: {
    INDEX: "/manager-result-image",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
  MANAGER_LEVEL: {
    INDEX: "/manager-level",
    TABLE: "",
    CREATE: "create",
    EDIT: "edit",
    DETAIL: "detail",
  },
};

export default PATH_URL;
